#version: '3'
#services:
#  cart:
#    build:
#      context: ./cart
#      dockerfile: Dockerfile
#    ports:
#      - "8081:8081"
#    depends_on:
#      - jaeger
#
#  order:
#    build:
#      context: ./order.svc
#      dockerfile: Dockerfile
#    ports:
#      - "8085:8085"
#    depends_on:
#      - jaeger
version: "3.9"
services:
  jaeger:
    image: jaegertracing/all-in-one:latest
    ports:
      - 4318:4318
      - 16686:16686
    environment:
      - COLLECTOR_OTLP_ENABLED=true
#  postgres:
#    container_name: postgres
#    image: postgres:latest
#    restart: always
#    environment:
#      POSTGRES_DB: opentelemetry
#      POSTGRES_USER: username
#      POSTGRES_PASSWORD: password
#    ports:
#      - "5432:5432"